### ISSUE TITLE
Can't build with python 3.12 (Windows)

### ISSUE THREAD

**Issue by kolbacer** [Relrin/kurier#21]
### **Description**

I am unable to build the project on Windows 11 when using Python 3.12.

### **Steps to Reproduce**
1. Follow the readme
 ```bash
   git clone https://github.com/Relrin/kurier.git
   cd kurier
   python -m venv venv
   ./venv/Scripts/activate
   pip install -r requirements.txt
   pip install -r requirements-build.txt
```

2. Observe the installation errors.

### **Observed Behavior**
`pip install -r requirements.txt` output:

<details>
  <summary>
    output
  </summary>
  Collecting wxPython==4.2.0 (from -r requirements.txt (line 1))
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      C:\Users\pc\AppData\Local\Temp\pip-install-s41kse7v\wxpython_13895771eff64afb9f4d3573c937c2e7\buildtools\config.py:1036: SyntaxWarning: invalid escape sequence '\s'
        result = re.search('^\s+SONAME\s+(.+)$', output, re.MULTILINE)
      Traceback (most recent call last):
        File "D:\kurier\kurier\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\kurier\kurier\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\kurier\kurier\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-w4mcctnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-w4mcctnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-w4mcctnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-w4mcctnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\Users\pc\AppData\Local\Temp\pip-install-s41kse7v\wxpython_13895771eff64afb9f4d3573c937c2e7\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
</details>

`pip install -r requirements-build.txt` output:

<details>
  <summary>
    output
  </summary>
  ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.10.0 Requires-Python <3.12,>=3.7; 5.10.1 Requires-Python <3.12,>=3.7; 5.11.0 Requires-Python <3.12,>=3.7; 5.12.0 Requires-Python <3.12,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7; 5.5 Requires-Python <3.12,>=3.7; 5.6 Requires-Python <3.12,>=3.7; 5.6.1 Requires-Python <3.12,>=3.7; 5.6.2 Requires-Python <3.12,>=3.7; 5.7.0 Requires-Python <3.12,>=3.7; 5.8.0 Requires-Python <3.12,>=3.7; 5.9.0 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement PyInstaller==5.7.0 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 6.8.0, 6.9.0, 6.10.0, 6.11.0, 6.11.1)
ERROR: No matching distribution found for PyInstaller==5.7.0
</details>

### **Expected Behavior**
The dependencies should install without errors, and the project should build successfully.

### **Environment Details**
- **Operating System**: Windows 11
- **Python Version**: 3.12.0
- **Pip Version**: 23.2.1
- **Branch/Commit**: `master/3215be8`

### **Possible Solutions**
Update dependencies or something.

**Comment by axelvestinsmhi** [comment]
same

**Comment by Relrin** [comment]
Hello!

Thanks for reporting an issue! I did manage to reproduce it at 3.12 versions. The output that was provided in the initial message points out on version conflict and the wxPython library. 

To resolve this issue I have bumped the versions of libraries to the latest ones, so it would be possible to build it under 3.12 as it should. Could you sync the latest changes from the `master` branch and then try again?

**Comment by axelvestinsmhi** [comment]
Hey, yes that worked better. Thanks.
